//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using HozestERP.BusinessLogic.CustomerManagement;

namespace HozestERP.BusinessLogic.Security
{
    public partial class ACL: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ACLID
        /// </summary>
        public int ACLID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerActionID
        /// </summary>
        public int CustomerActionID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerRoleID
        /// </summary>
        public int CustomerRoleID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Allow
        /// </summary>
        public bool Allow { get; set; }

        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the CustomerAction
        /// </summary>
        public virtual CustomerAction SCustomerAction { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerRole
        /// </summary>
        public virtual CustomerRole SCustomerRole { get; set; }

        #endregion
    }
}
