//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.CustomerManagement;
using HozestERP.BusinessLogic.ModuleManagement;

namespace HozestERP.BusinessLogic.Security
{
    public partial class ACLModule: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ACLPerObjectId
        /// </summary>
        public int ACLModuleId { get; set; }
    
    	/// <summary>
        /// Gets or sets the ModuleID
        /// </summary>
        public int ModuleID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerRoleId
        /// </summary>
        public int CustomerRoleId { get; set; }
    
    	/// <summary>
        /// Gets or sets the Deny
        /// </summary>
        public bool Allow { get; set; }

        #endregion
        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the CustomerRole
        /// </summary>
        public virtual CustomerRole SCustomerRole { get; set; }

        #endregion
    }
}
