//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using HozestERP.BusinessLogic.CustomerManagement;

using HozestERP.BusinessLogic.Infrastructure;

namespace HozestERP.BusinessLogic.Audit
{
    public partial class ActivityLog: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ActivityLogID
        /// </summary>
        public int ActivityLogID { get; set; }
    
    	/// <summary>
        /// Gets or sets the ActivityLogTypeID
        /// </summary>
        public int ActivityLogTypeID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Comment
        /// </summary>
        public string Comment { get; set; }
    
    	/// <summary>
        /// Gets or sets the CreatedOn
        /// </summary>
        public System.DateTime CreatedOn { get; set; }

        /// <summary>
        /// …Ãº“ID 
        /// </summary>
        public int? MerchantID { get; set; }

        #endregion


        #region Custom properties

        /// <summary>
        /// Gets the activity log type
        /// </summary>
        public ActivityLogType ActivityLogType
        {
            get
            {
                return IoC.Resolve<ICustomerActivityService>().GetActivityTypeById(this.ActivityLogTypeID);
            }
        }

        /// <summary>
        /// Gers the customer
        /// </summary>
        public Customer Customer
        {
            get
            {
                return IoC.Resolve<ICustomerService>().GetCustomerById(this.CustomerID);
            }
        }

        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the ActivityLogType
        /// </summary>
        public virtual ActivityLogType SActivityLogType { get; set; }
    
    	/// <summary>
        /// Gets or sets the Customer
        /// </summary>
        public virtual Customer SCustomer { get; set; }

        #endregion
    }
}
