//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace HozestERP.BusinessLogic.Audit
{
    public partial class ActivityLogType: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ActivityLogTypeID
        /// </summary>
        public int ActivityLogTypeID { get; set; }
    
    	/// <summary>
        /// Gets or sets the SystemKeyword
        /// </summary>
        public string SystemKeyword { get; set; }
    
    	/// <summary>
        /// Gets or sets the Name
        /// </summary>
        public string Name { get; set; }
    
    	/// <summary>
        /// Gets or sets the Enabled
        /// </summary>
        public bool Enabled { get; set; }

        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the ActivityLog list
        /// </summary>
        public virtual ICollection<ActivityLog> SActivityLogs { get; set; }

        #endregion
    }
}
