//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using HozestERP.BusinessLogic.CustomerManagement;
using HozestERP.BusinessLogic.Infrastructure;

namespace HozestERP.BusinessLogic.Audit
{
    public partial class Log: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the LogID
        /// </summary>
        public int LogID { get; set; }
    
    	/// <summary>
        /// Gets or sets the LogTypeID
        /// </summary>
        public int LogTypeID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Severity
        /// </summary>
        public int Severity { get; set; }
    
    	/// <summary>
        /// Gets or sets the Message
        /// </summary>
        public string Message { get; set; }
    
    	/// <summary>
        /// Gets or sets the Exception
        /// </summary>
        public string Exception { get; set; }
    
    	/// <summary>
        /// Gets or sets the IPAddress
        /// </summary>
        public string IPAddress { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the PageURL
        /// </summary>
        public string PageURL { get; set; }
    
    	/// <summary>
        /// Gets or sets the ReferrerURL
        /// </summary>
        public string ReferrerURL { get; set; }
    
    	/// <summary>
        /// Gets or sets the CreatedOn
        /// </summary>
        public System.DateTime CreatedOn { get; set; }

        #endregion

        #region Custom Properties

        /// <summary>
        /// Gets the customer
        /// </summary>
        public Customer Customer
        {
            get
            {
                return IoC.Resolve<ICustomerService>().GetCustomerById(this.CustomerID);
            }
        }
        /// <summary>
        /// Gets the log type
        /// </summary>
        public LogTypeEnum LogType
        {
            get
            {
                return (LogTypeEnum)this.LogTypeID;
            }
        }
        #endregion
    }
}
