//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HozestERP.Web.JDsingleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JDsingleServiceReference.JDsingleOrderGetSoap")]
    public interface JDsingleOrderGetSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebGetJDOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdObject))]
        HozestERP.Web.JDsingleServiceReference.OrderInfo WebGetJDOrderInfo(string orderId, string AppKey, string AppSecret, string ServerUrl, string AccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebGetJDOrderInfoAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdObject))]
        HozestERP.Web.JDsingleServiceReference.OrderInfo[] WebGetJDOrderInfoAll(System.DateTime startDate, System.DateTime endDate, string orderState, int page, int pageSize, bool recursive, string AppKey, string AppSecret, string ServerUrl, string AccessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutstorage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JdObject))]
        HozestERP.Web.JDsingleServiceReference.JindingOutstoragePesponse GetOutstorage(string OrderId, string LogisticsId, string Waybill, string AppKey, string AppSecret, string ServerUrl, string AccessToken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderInfo : JdObject {
        
        private string order_idField;
        
        private string vender_idField;
        
        private string pay_typeField;
        
        private string order_total_priceField;
        
        private string order_paymentField;
        
        private string order_seller_priceField;
        
        private string freight_priceField;
        
        private string seller_discountField;
        
        private string order_stateField;
        
        private string order_state_remarkField;
        
        private string delivery_typeField;
        
        private string invoice_infoField;
        
        private string order_remarkField;
        
        private string order_start_timeField;
        
        private string order_end_timeField;
        
        private UserInfo consignee_infoField;
        
        private ItemInfo[] item_info_listField;
        
        private CouponDetail[] coupon_detail_listField;
        
        private string return_orderField;
        
        private string vender_remarkField;
        
        private string pinField;
        
        private string balance_usedField;
        
        private string modifiedField;
        
        private string payment_confirm_timeField;
        
        private string logistics_idField;
        
        private string waybillField;
        
        private VatInvoiceInfo vat_invoice_infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vender_id {
            get {
                return this.vender_idField;
            }
            set {
                this.vender_idField = value;
                this.RaisePropertyChanged("vender_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pay_type {
            get {
                return this.pay_typeField;
            }
            set {
                this.pay_typeField = value;
                this.RaisePropertyChanged("pay_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string order_total_price {
            get {
                return this.order_total_priceField;
            }
            set {
                this.order_total_priceField = value;
                this.RaisePropertyChanged("order_total_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string order_payment {
            get {
                return this.order_paymentField;
            }
            set {
                this.order_paymentField = value;
                this.RaisePropertyChanged("order_payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string order_seller_price {
            get {
                return this.order_seller_priceField;
            }
            set {
                this.order_seller_priceField = value;
                this.RaisePropertyChanged("order_seller_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string freight_price {
            get {
                return this.freight_priceField;
            }
            set {
                this.freight_priceField = value;
                this.RaisePropertyChanged("freight_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string seller_discount {
            get {
                return this.seller_discountField;
            }
            set {
                this.seller_discountField = value;
                this.RaisePropertyChanged("seller_discount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string order_state {
            get {
                return this.order_stateField;
            }
            set {
                this.order_stateField = value;
                this.RaisePropertyChanged("order_state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string order_state_remark {
            get {
                return this.order_state_remarkField;
            }
            set {
                this.order_state_remarkField = value;
                this.RaisePropertyChanged("order_state_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string delivery_type {
            get {
                return this.delivery_typeField;
            }
            set {
                this.delivery_typeField = value;
                this.RaisePropertyChanged("delivery_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string invoice_info {
            get {
                return this.invoice_infoField;
            }
            set {
                this.invoice_infoField = value;
                this.RaisePropertyChanged("invoice_info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string order_remark {
            get {
                return this.order_remarkField;
            }
            set {
                this.order_remarkField = value;
                this.RaisePropertyChanged("order_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string order_start_time {
            get {
                return this.order_start_timeField;
            }
            set {
                this.order_start_timeField = value;
                this.RaisePropertyChanged("order_start_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string order_end_time {
            get {
                return this.order_end_timeField;
            }
            set {
                this.order_end_timeField = value;
                this.RaisePropertyChanged("order_end_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public UserInfo consignee_info {
            get {
                return this.consignee_infoField;
            }
            set {
                this.consignee_infoField = value;
                this.RaisePropertyChanged("consignee_info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item_info_list", Order=16)]
        public ItemInfo[] item_info_list {
            get {
                return this.item_info_listField;
            }
            set {
                this.item_info_listField = value;
                this.RaisePropertyChanged("item_info_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coupon_detail_list", Order=17)]
        public CouponDetail[] coupon_detail_list {
            get {
                return this.coupon_detail_listField;
            }
            set {
                this.coupon_detail_listField = value;
                this.RaisePropertyChanged("coupon_detail_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string return_order {
            get {
                return this.return_orderField;
            }
            set {
                this.return_orderField = value;
                this.RaisePropertyChanged("return_order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string vender_remark {
            get {
                return this.vender_remarkField;
            }
            set {
                this.vender_remarkField = value;
                this.RaisePropertyChanged("vender_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string balance_used {
            get {
                return this.balance_usedField;
            }
            set {
                this.balance_usedField = value;
                this.RaisePropertyChanged("balance_used");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string payment_confirm_time {
            get {
                return this.payment_confirm_timeField;
            }
            set {
                this.payment_confirm_timeField = value;
                this.RaisePropertyChanged("payment_confirm_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string logistics_id {
            get {
                return this.logistics_idField;
            }
            set {
                this.logistics_idField = value;
                this.RaisePropertyChanged("logistics_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string waybill {
            get {
                return this.waybillField;
            }
            set {
                this.waybillField = value;
                this.RaisePropertyChanged("waybill");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public VatInvoiceInfo vat_invoice_info {
            get {
                return this.vat_invoice_infoField;
            }
            set {
                this.vat_invoice_infoField = value;
                this.RaisePropertyChanged("vat_invoice_info");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo : JdObject {
        
        private string fullnameField;
        
        private string full_addressField;
        
        private string telephoneField;
        
        private string mobileField;
        
        private string provinceField;
        
        private string cityField;
        
        private string countyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
                this.RaisePropertyChanged("fullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string full_address {
            get {
                return this.full_addressField;
            }
            set {
                this.full_addressField = value;
                this.RaisePropertyChanged("full_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
                this.RaisePropertyChanged("telephone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string county {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("county");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VatInvoiceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CouponDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class JdObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JindingOutstoragePesponseOP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string order_idField;
        
        private string vender_idField;
        
        private string modifiedField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vender_id {
            get {
                return this.vender_idField;
            }
            set {
                this.vender_idField = value;
                this.RaisePropertyChanged("vender_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JindingOutstoragePesponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class JdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string errMsgField;
        
        private string zh_descField;
        
        private string en_descField;
        
        private string bodyField;
        
        private string reqUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("ErrMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string zh_desc {
            get {
                return this.zh_descField;
            }
            set {
                this.zh_descField = value;
                this.RaisePropertyChanged("zh_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string en_desc {
            get {
                return this.en_descField;
            }
            set {
                this.en_descField = value;
                this.RaisePropertyChanged("en_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReqUrl {
            get {
                return this.reqUrlField;
            }
            set {
                this.reqUrlField = value;
                this.RaisePropertyChanged("ReqUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JindingOutstoragePesponse : JdResponse {
        
        private JindingOutstoragePesponseOP order_sop_outstorage_responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public JindingOutstoragePesponseOP order_sop_outstorage_response {
            get {
                return this.order_sop_outstorage_responseField;
            }
            set {
                this.order_sop_outstorage_responseField = value;
                this.RaisePropertyChanged("order_sop_outstorage_response");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VatInvoiceInfo : JdObject {
        
        private string taxpayer_identField;
        
        private string registered_addressField;
        
        private string registered_phoneField;
        
        private string deposit_bankField;
        
        private string bank_accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taxpayer_ident {
            get {
                return this.taxpayer_identField;
            }
            set {
                this.taxpayer_identField = value;
                this.RaisePropertyChanged("taxpayer_ident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string registered_address {
            get {
                return this.registered_addressField;
            }
            set {
                this.registered_addressField = value;
                this.RaisePropertyChanged("registered_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string registered_phone {
            get {
                return this.registered_phoneField;
            }
            set {
                this.registered_phoneField = value;
                this.RaisePropertyChanged("registered_phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deposit_bank {
            get {
                return this.deposit_bankField;
            }
            set {
                this.deposit_bankField = value;
                this.RaisePropertyChanged("deposit_bank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bank_account {
            get {
                return this.bank_accountField;
            }
            set {
                this.bank_accountField = value;
                this.RaisePropertyChanged("bank_account");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CouponDetail : JdObject {
        
        private string coupon_priceField;
        
        private string coupon_typeField;
        
        private string order_idField;
        
        private string sku_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string coupon_price {
            get {
                return this.coupon_priceField;
            }
            set {
                this.coupon_priceField = value;
                this.RaisePropertyChanged("coupon_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string coupon_type {
            get {
                return this.coupon_typeField;
            }
            set {
                this.coupon_typeField = value;
                this.RaisePropertyChanged("coupon_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sku_id {
            get {
                return this.sku_idField;
            }
            set {
                this.sku_idField = value;
                this.RaisePropertyChanged("sku_id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemInfo : JdObject {
        
        private string sku_idField;
        
        private string outer_sku_idField;
        
        private string sku_nameField;
        
        private string jd_priceField;
        
        private string gift_pointField;
        
        private string ware_idField;
        
        private string item_totalField;
        
        private string product_noField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sku_id {
            get {
                return this.sku_idField;
            }
            set {
                this.sku_idField = value;
                this.RaisePropertyChanged("sku_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string outer_sku_id {
            get {
                return this.outer_sku_idField;
            }
            set {
                this.outer_sku_idField = value;
                this.RaisePropertyChanged("outer_sku_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sku_name {
            get {
                return this.sku_nameField;
            }
            set {
                this.sku_nameField = value;
                this.RaisePropertyChanged("sku_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string jd_price {
            get {
                return this.jd_priceField;
            }
            set {
                this.jd_priceField = value;
                this.RaisePropertyChanged("jd_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string gift_point {
            get {
                return this.gift_pointField;
            }
            set {
                this.gift_pointField = value;
                this.RaisePropertyChanged("gift_point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ware_id {
            get {
                return this.ware_idField;
            }
            set {
                this.ware_idField = value;
                this.RaisePropertyChanged("ware_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string item_total {
            get {
                return this.item_totalField;
            }
            set {
                this.item_totalField = value;
                this.RaisePropertyChanged("item_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string product_no {
            get {
                return this.product_noField;
            }
            set {
                this.product_noField = value;
                this.RaisePropertyChanged("product_no");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JDsingleOrderGetSoapChannel : HozestERP.Web.JDsingleServiceReference.JDsingleOrderGetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JDsingleOrderGetSoapClient : System.ServiceModel.ClientBase<HozestERP.Web.JDsingleServiceReference.JDsingleOrderGetSoap>, HozestERP.Web.JDsingleServiceReference.JDsingleOrderGetSoap {
        
        public JDsingleOrderGetSoapClient() {
        }
        
        public JDsingleOrderGetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JDsingleOrderGetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDsingleOrderGetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDsingleOrderGetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HozestERP.Web.JDsingleServiceReference.OrderInfo WebGetJDOrderInfo(string orderId, string AppKey, string AppSecret, string ServerUrl, string AccessToken) {
            return base.Channel.WebGetJDOrderInfo(orderId, AppKey, AppSecret, ServerUrl, AccessToken);
        }
        
        public HozestERP.Web.JDsingleServiceReference.OrderInfo[] WebGetJDOrderInfoAll(System.DateTime startDate, System.DateTime endDate, string orderState, int page, int pageSize, bool recursive, string AppKey, string AppSecret, string ServerUrl, string AccessToken) {
            return base.Channel.WebGetJDOrderInfoAll(startDate, endDate, orderState, page, pageSize, recursive, AppKey, AppSecret, ServerUrl, AccessToken);
        }
        
        public HozestERP.Web.JDsingleServiceReference.JindingOutstoragePesponse GetOutstorage(string OrderId, string LogisticsId, string Waybill, string AppKey, string AppSecret, string ServerUrl, string AccessToken) {
            return base.Channel.GetOutstorage(OrderId, LogisticsId, Waybill, AppKey, AppSecret, ServerUrl, AccessToken);
        }
    }
}
