//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using HozestERP.BusinessLogic.CustomerManagement;

namespace HozestERP.BusinessLogic.ManageProtal
{
    public partial class PortalColumnNumber: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ID
        /// </summary>
        public int ID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Width
        /// </summary>
        public decimal Width { get; set; }
    
    	/// <summary>
        /// Gets or sets the Display
        /// </summary>
        public int Display { get; set; }

        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the HCustomerInfo
        /// </summary>
        public virtual Customer SCustomer { get; set; }

        /// <summary>
        /// Gets or sets the SPortalColumnNumbers list
        /// </summary>
        public virtual ICollection<PortalColumn> SPortalColumns { get; set; }

        #endregion
    }
}
