//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.Linq;

using HozestERP.BusinessLogic.Audit;
using HozestERP.BusinessLogic.Infrastructure;
using HozestERP.BusinessLogic.Enterprises;
using HozestERP.BusinessLogic.Profile;
using HozestERP.BusinessLogic.Media;
using HozestERP.BusinessLogic.Codes;
using HozestERP.BusinessLogic.ManageProtal;

namespace HozestERP.BusinessLogic.CustomerManagement
{
    public partial class Customer: BaseEntity
    {
        #region Fields


        private List<CustomerRole> _customerRolesCache;
        //private Address _billingAddressCache;
        //private Address _shippingAddressCache;
        //private List<RewardPointsHistory> _rewardPointsHistoryCache;

        #endregion
        
        private List<CustomerAttribute> _customerAttributesCache;
        /// <summary>
        /// Resets cached values for an instance
        /// </summary>
        public void ResetCachedValues()
        {
            _customerAttributesCache = null;
        }

        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }

        /// <summary>
        /// Gets or sets the CustomerGUID
        /// </summary>
        public Guid CustomerGUID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Email
        /// </summary>
        public string Email { get; set; }
    
    	/// <summary>
        /// Gets or sets the Username
        /// </summary>
        public string Username { get; set; }
    
    	/// <summary>
        /// Gets or sets the PasswordHash
        /// </summary>
        public string PasswordHash { get; set; }
    
    	/// <summary>
        /// Gets or sets the SaltKey
        /// </summary>
        public string SaltKey { get; set; }

    	/// <summary>
        /// Gets or sets the IsAdmin
        /// </summary>
        public bool IsAdmin { get; set; }
    
    	/// <summary>
        /// Gets or sets the IsGuest
        /// </summary>
        public bool IsGuest { get; set; }
    
    	/// <summary>
        /// Gets or sets the Signature
        /// </summary>
        public string Signature { get; set; }
    
    	/// <summary>
        /// Gets or sets the AdminComment
        /// </summary>
        public string AdminComment { get; set; }
    
    	/// <summary>
        /// Gets or sets the Active
        /// </summary>
        public bool Active { get; set; }
    
    	/// <summary>
        /// Gets or sets the Deleted
        /// </summary>
        public bool Deleted { get; set; }
    
    	/// <summary>
        /// Gets or sets the RegistrationDate
        /// </summary>
        public System.DateTime RegistrationDate { get; set; }
    
    	/// <summary>
        /// Gets or sets the TimeZoneID
        /// </summary>
        public string TimeZoneID { get; set; }
    
    	/// <summary>
        /// Gets or sets the AvatarID
        /// </summary>
        public int AvatarID { get; set; }
    
    	/// <summary>
        /// Gets or sets the DateOfBirth
        /// </summary>
        public Nullable<System.DateTime> DateOfBirth { get; set; }


        #endregion

        #region Custom Properties
        /// <summary>
        /// Gets the customer attributes
        /// </summary>
        public List<CustomerAttribute> CustomerAttributes
        {
            get
            {
                if (_customerAttributesCache == null)
                    _customerAttributesCache = IoC.Resolve<ICustomerService>().GetCustomerAttributesByCustomerId(this.CustomerID);

                return _customerAttributesCache;
            }
        }
        /// <summary>
        /// Gets the customer roles
        /// </summary>
        public List<CustomerRole> CustomerRoles
        {
            get
            {
                if (_customerRolesCache == null)
                    _customerRolesCache = IoC.Resolve<ICustomerService>().GetCustomerRolesByCustomerId(this.CustomerID);

                return _customerRolesCache;
            }
        }

        /// <summary>
        /// Gets the avatar
        /// </summary>
        public Picture Avatar
        {
            get
            {
                return IoC.Resolve<IPictureService>().GetPictureById(this.AvatarID);
            }
        }

        /// <summary>
        /// Gets or sets the page theme
        /// </summary>
        public string WorkingTheme
        {
            get
            {
                var customerAttributes = this.CustomerAttributes;
                CustomerAttribute attr = customerAttributes.FindAttribute("WorkingTheme", this.CustomerID);
                if (attr != null)
                {
                    return attr.Value;
                }
                else
                    return "Blue";
            }
            set
            {
                var customerAttributes = this.CustomerAttributes;
                CustomerAttribute attr = customerAttributes.FindAttribute("WorkingTheme", this.CustomerID);
                if (attr != null)
                {
                    attr.Value = value.ToString();
                    IoC.Resolve<ICustomerService>().UpdateCustomerAttribute(attr);
                }
                else
                {
                    attr = new CustomerAttribute()
                    {
                        CustomerId = this.CustomerID,
                        Key = "WorkingTheme",
                        Value = value
                    };
                    IoC.Resolve<ICustomerService>().InsertCustomerAttribute(attr);
                }
                ResetCachedValues();
            }
        }

        #endregion       

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the ActivityLog list
        /// </summary>
        public virtual ICollection<ActivityLog> SActivityLogs { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerAttribute list
        /// </summary>
        public virtual ICollection<CustomerAttribute> SCustomerAttributes { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerRole list
        /// </summary>
        public virtual ICollection<CustomerRole> SCustomerRoles { get; set; }

        /// <summary>
        /// Gets or sets the PortalColumnNumber list
        /// </summary>
        public virtual ICollection<PortalColumnNumber> SPortalColumnNumbers { get; set; }

        /// <summary>
        /// Gets or sets the SCustomerInfo
        /// </summary>
        /// 
        /// </summary>
        public virtual CustomerInfo SCustomerInfo { get; set; }
       

        /// <summary>
        /// °üº¬ÓÃ»§
        /// </summary>
        public virtual ICollection<CustomerRole> SStaffPrivilegesCustomerRole { get; set; }

        #endregion
    }
}
