//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.Security;
using HozestERP.BusinessLogic.ModuleManagement;
using HozestERP.BusinessLogic.Infrastructure;

namespace HozestERP.BusinessLogic.CustomerManagement
{
    public partial class CustomerAction: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the CustomerActionID
        /// </summary>
        public int CustomerActionID { get; set; }

        /// <summary>
        /// Gets or sets the ModuleID
        /// </summary>
        public int ModuleID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Name
        /// </summary>
        public string Name { get; set; }
    
    	/// <summary>
        /// Gets or sets the SystemKeyword
        /// </summary>
        public string SystemKeyword { get; set; }
    
    	/// <summary>
        /// Gets or sets the Comment
        /// </summary>
        public string Comment { get; set; }
    
    	/// <summary>
        /// Gets or sets the DisplayOrder
        /// </summary>
        public int DisplayOrder { get; set; }

        #endregion

        #region Customer Properties
        /// <summary>
        /// 
        /// </summary>
        public Module Module
        {
            get
            {
                return IoC.Resolve<IModuleService>().getModuleByModuleID(this.ModuleID);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ModuleName
        {
            get
            {
                if (this.Module != null)
                    return this.Module.ModuleName;
                return string.Empty;
            }
        }
        #endregion

        #region Navigation Properties

        /// <summary>
        /// Gets or sets the ACL list
        /// </summary>
        public virtual ICollection<ACL> SACLs { get; set; }

        /// <summary>
        /// Gets or sets the Module 
        /// </summary>
        public virtual Module SModule { get; set; }

        #endregion
    }
}
