//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.Infrastructure;

namespace HozestERP.BusinessLogic.CustomerManagement
{
    public partial class CustomerSession: BaseEntity
    {       
        #region Fields
        private Customer _customer;
        #endregion 

        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the CustomerSessionGUID
        /// </summary>
        public System.Guid CustomerSessionGUID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }

        /// <summary>
        /// Gets or sets the LogTime
        /// </summary>
        public System.DateTime LogTime { get; set; }
    
    	/// <summary>
        /// Gets or sets the LastAccessed
        /// </summary>
        public System.DateTime LastAccessed { get; set; }
    
    	/// <summary>
        /// Gets or sets the IsExpired
        /// </summary>
        public bool IsExpired { get; set; }

        #endregion


        #region Custom Properties
        /// <summary>
        /// Gets or sets the customer
        /// </summary>
        public Customer Customer
        {
            get
            {
                if (_customer == null)
                    _customer = IoC.Resolve<ICustomerService>().GetCustomerById(this.CustomerID);
                return _customer;
            }
        }
        #endregion
    }
}
