//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using HozestERP.BusinessLogic.Codes;
using HozestERP.BusinessLogic.Enterprises;
using HozestERP.BusinessLogic.Infrastructure;
using HozestERP.BusinessLogic.ManageBulletin; 

namespace HozestERP.BusinessLogic.CustomerManagement
{
    public partial class CustomerInfo: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the DepartmentID
        /// </summary>
        public int DepartmentID { get; set; }
    
    	/// <summary>
        /// Gets or sets the JobNumber
        /// </summary>
        public string JobNumber { get; set; }

        /// <summary>
        /// Gets or sets the IDNumber
        /// </summary>
        public string IDNumber { get; set; }
    
    	/// <summary>
        /// Gets or sets the FullName
        /// </summary>
        public string FullName { get; set; }
    
    	/// <summary>
        /// Gets or sets the GenderID
        /// </summary>
        public int GenderID { get; set; }
    
    	/// <summary>
        /// Gets or sets the NationalityID
        /// </summary>
        public int NationalityID { get; set; }
    
    	/// <summary>
        /// Gets or sets the AnimalID
        /// </summary>
        public int AnimalID { get; set; }
    
    	/// <summary>
        /// Gets or sets the RegisteredResidence
        /// </summary>
        public string RegisteredResidence { get; set; }
    
    	/// <summary>
        /// Gets or sets the Birthday
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
    
    	/// <summary>
        /// Gets or sets the MarriageID
        /// </summary>
        public Nullable<int> MarriageID { get; set; }
    
    	/// <summary>
        /// Gets or sets the BloodTypeID
        /// </summary>
        public int BloodTypeID { get; set; }
    
    	/// <summary>
        /// Gets or sets the PoliticalStatusID
        /// </summary>
        public Nullable<int> PoliticalStatusID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Stature
        /// </summary>
        public int Stature { get; set; }
    
    	/// <summary>
        /// Gets or sets the Childbearing
        /// </summary>
        public bool Childbearing { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerStatusID
        /// </summary>
        public int CustomerStatusID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Deleted
        /// </summary>
        public bool Deleted { get; set; }
    
    	/// <summary>
        /// Gets or sets the Published
        /// </summary>
        public bool Published { get; set; }
    
    	/// <summary>
        /// Gets or sets the DisplayOrder
        /// </summary>
        public int DisplayOrder { get; set; }
    
    	/// <summary>
        /// Gets or sets the Created
        /// </summary>
        public Nullable<System.DateTime> Created { get; set; }
    
    	/// <summary>
        /// Gets or sets the CreatorID
        /// </summary>
        public Nullable<int> CreatorID { get; set; }

        #endregion

        #region Customer Properties
        /// <summary>
        /// 性别
        /// </summary>
        public CodeList Gender
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.GenderID);
            }
        }

        /// <summary>
        /// 在职状态
        /// </summary>
        public CustomerStatusEnum CustomerStatus
        {
            get
            {
                return (CustomerStatusEnum)this.CustomerStatusID;
            }
            set
            {
                this.CustomerStatusID = (int)value;
            }
        }

        /// <summary>
        /// 民族
        /// </summary>
        public CodeList Nationality
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.NationalityID);
            }
        }

        /// <summary>
        /// 生肖
        /// </summary>
        public CodeList Animal
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.AnimalID);
            }
        }

        /// <summary>
        /// 婚姻状况
        /// </summary>
        public CodeList Marriage
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.MarriageID.GetValueOrDefault());
            }
        }

        /// <summary>
        /// 血型
        /// </summary>
        public CodeList BloodType
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.BloodTypeID);
            }
        }

        /// <summary>
        /// 变动类型
        /// </summary>
        public CodeList ChangeType
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.CustomerStatusID);
            }
        }

        /// <summary>
        /// 政治面貌
        /// </summary>
        public CodeList PoliticalStatus
        {
            get
            {
                return IoC.Resolve<ICodeService>().GetCodeListInfoByCodeID(this.PoliticalStatusID.GetValueOrDefault());
            }
        }
        
        /// <summary>
        /// 部门名称
        /// </summary>
        public string DepartmentName
        {
            get
            {
                var department = IoC.Resolve<IEnterpriseService>().GetDepartmentById(this.DepartmentID);
                if (department != null)
                    return department.DepName;
                return string.Empty;
            }
        }

        /// <summary>
        /// 星级ID
        /// </summary>
        public decimal StarLv
        {
            get
            {
                var customerStar = IoC.Resolve<ICustomerInfoService>().GetCustomerStarByCustomerID(this.CustomerID);
                if (customerStar != null)
                    return customerStar.StarLv;
                return 1;
            }
        }

        /// <summary>
        /// 可操作客户数
        /// </summary>
        public int ServerCount
        {
            get
            {
                var customerStar = IoC.Resolve<ICustomerInfoService>().GetCustomerStarByCustomerID(this.CustomerID);
                if (customerStar != null)
                    return customerStar.ServerCount.Value;
                return 0;
            }
        }

        /// <summary>
        /// 上次星级
        /// </summary>
        public string Spare2
        {
            get
            {
                var customerStar = IoC.Resolve<ICustomerInfoService>().GetCustomerStarByCustomerID(this.CustomerID);
                if (customerStar != null)
                    return customerStar.Spare2;
                return null;
            }
        }

        /// <summary>
        /// 擅长
        /// </summary>
        public string Spare1
        {
            get
            {
                var customerStar = IoC.Resolve<ICustomerInfoService>().GetCustomerStarByCustomerID(this.CustomerID);
                if (customerStar != null)
                    return customerStar.Spare1;
                return null;
            }
        }
        #endregion

        #region Navigation Properties

        /// <summary>
        /// Gets or sets the SCustomer
        /// </summary>
        /// 
        /// </summary>
        public virtual Customer SCustomer { get; set; }
    
    	/// <summary>
        /// Gets or sets the SDepartment
        /// </summary>
        /// 
        /// </summary>
        public virtual Department SDepartment { get; set; }

        /// <summary>
        /// 公告通知
        /// </summary>
        public virtual ICollection<Bulletin> SBulletins { get; set; }
         
        #endregion
    }
}
