//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace HozestERP.BusinessLogic.CustomerManagement
{
    public partial class Sys_CustomerStar: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the ID
        /// </summary>
        public int ID { get; set; }
    
    	/// <summary>
        /// Gets or sets the CustomerID
        /// </summary>
        public int CustomerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the StarLv
        /// </summary>
        public decimal StarLv { get; set; }
    
    	/// <summary>
        /// Gets or sets the ServerCount
        /// </summary>
        public Nullable<int> ServerCount { get; set; }
    
    	/// <summary>
        /// Gets or sets the IsNew
        /// </summary>
        public Nullable<bool> IsNew { get; set; }
    
    	/// <summary>
        /// Gets or sets the SetID
        /// </summary>
        public int SetID { get; set; }
    
    	/// <summary>
        /// Gets or sets the SetDate
        /// </summary>
        public System.DateTime SetDate { get; set; }
    
    	/// <summary>
        /// Gets or sets the Spare1
        /// </summary>
        public string Spare1 { get; set; }
    
    	/// <summary>
        /// Gets or sets the Spare2
        /// </summary>
        public string Spare2 { get; set; }

        #endregion
    }
}
