//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;


namespace HozestERP.BusinessLogic.Media
{
    public partial class Picture: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the PictureID
        /// </summary>
        public int PictureID { get; set; }
    
    	/// <summary>
        /// Gets or sets the PictureBinary
        /// </summary>
        public byte[] PictureBinary { get; set; }
    
    	/// <summary>
        /// Gets or sets the IsNew
        /// </summary>
        public bool IsNew { get; set; }
    
    	/// <summary>
        /// Gets or sets the MimeType
        /// </summary>
        public string MimeType { get; set; }

        #endregion
    }
}
