//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.CustomerManagement;
using HozestERP.BusinessLogic.Infrastructure;

namespace HozestERP.BusinessLogic.Enterprises
{
    public partial class Department: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the DepartmentID
        /// </summary>
        public int DepartmentID { get; set; }
    
    	/// <summary>
        /// Gets or sets the ParentID
        /// </summary>
        public Nullable<int> ParentID { get; set; }
    
    	/// <summary>
        /// Gets or sets the EnterpriseID
        /// </summary>
        public int EnterpriseID { get; set; }
    
    	/// <summary>
        /// Gets or sets the DepCode
        /// </summary>
        public string DepCode { get; set; }
    
    	/// <summary>
        /// Gets or sets the DepName
        /// </summary>
        public string DepName { get; set; }
    
    	/// <summary>
        /// Gets or sets the DepType
        /// </summary>
        public Nullable<int> DepType { get; set; }
    
    	/// <summary>
        /// Gets or sets the Label
        /// </summary>
        public string Label { get; set; }

        /// <summary>
        /// 获取/设置 部门主管
        /// </summary>
        public int DepManagerID { get; set; }
    
    	/// <summary>
        /// Gets or sets the Address
        /// </summary>
        public string Address { get; set; }
    
    	/// <summary>
        /// Gets or sets the Tel
        /// </summary>
        public string Tel { get; set; }
    
    	/// <summary>
        /// Gets or sets the Published
        /// </summary>
        public bool Published { get; set; }
    
    	/// <summary>
        /// Gets or sets the Deleted
        /// </summary>
        public bool Deleted { get; set; }
    
    	/// <summary>
        /// Gets or sets the DisplayOrder
        /// </summary>
        public int DisplayOrder { get; set; }
    
    	/// <summary>
        /// Gets or sets the Remark
        /// </summary>
        public string Remark { get; set; }
    
    	/// <summary>
        /// Gets or sets the AddUserId
        /// </summary>
        public Nullable<int> AddUserId { get; set; }
    
    	/// <summary>
        /// Gets or sets the AddTime
        /// </summary>
        public string AddTime { get; set; }
    
    	/// <summary>
        /// Gets or sets the EditUserId
        /// </summary>
        public Nullable<int> EditUserId { get; set; }
    
    	/// <summary>
        /// Gets or sets the EditTime
        /// </summary>
        public string EditTime { get; set; }

        #endregion

        #region Customer Properties
        /// <summary>
        /// 
        /// </summary>
        public Department ParentDepartment
        {
            get
            {
                return IoC.Resolve<IEnterpriseService>().GetDepartmentById(this.ParentID.GetValueOrDefault());
            }
        }

        /// <summary>
        /// Get the CustomerInfo
        /// </summary>
        public CustomerInfo DepManager
        {
            get
            {
                return IoC.Resolve<ICustomerInfoService>().GetCustomerInfoByID(this.DepManagerID);
            }
        }
        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the SEnterprise
        /// </summary>
        public virtual Enterprise SEnterprise { get; set; }

        /// <summary>
        /// Gets or sets the SCustomerInfos list
        /// </summary>
        public virtual ICollection<CustomerInfo> SCustomerInfos { get; set; }


        /// <summary>
        /// Gets or sets the CustomerRole list
        /// </summary>
        public virtual ICollection<CustomerRole> SCustomerRoles { get; set; }

        #endregion
    }
}
