//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.CustomerManagement;

namespace HozestERP.BusinessLogic.Enterprises
{
    public partial class Enterprise: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the 主键
        /// </summary>
        public int EntId { get; set; }
    
    	/// <summary>
        /// Gets or sets the 名称
        /// </summary>
        public string EntName { get; set; }
    
    	/// <summary>
        /// Gets or sets the 电话
        /// </summary>
        public string EntTel { get; set; }
    
    	/// <summary>
        /// Gets or sets the 传真
        /// </summary>
        public string EntFax { get; set; }
    
    	/// <summary>
        /// Gets or sets the 地址
        /// </summary>
        public string EntAddress { get; set; }
    
    	/// <summary>
        /// Gets or sets the 邮编
        /// </summary>
        public string EntZip { get; set; }
    
    	/// <summary>
        /// Gets or sets the 网址
        /// </summary>
        public string EntWebSite { get; set; }
    
    	/// <summary>
        /// Gets or sets the 电子邮件
        /// </summary>
        public string EntEmail { get; set; }
    
    	/// <summary>
        /// Gets or sets the 开户行
        /// </summary>
        public string EntBank { get; set; }
    
    	/// <summary>
        /// Gets or sets the 账号
        /// </summary>
        public string EntBankAccount { get; set; }
    
    	/// <summary>
        /// Gets or sets the AddUserId
        /// </summary>
        public int AddUserId { get; set; }
    
    	/// <summary>
        /// Gets or sets the AddTime
        /// </summary>
        public string AddTime { get; set; }
    
    	/// <summary>
        /// Gets or sets the Published
        /// </summary>
        public bool Published { get; set; }
    
    	/// <summary>
        /// Gets or sets the Deleted
        /// </summary>
        public bool Deleted { get; set; }
    
    	/// <summary>
        /// Gets or sets the 序号
        /// </summary>
        public int DisplayOrder { get; set; }

        #endregion

        #region Navigation Properties
    
    	/// <summary>
        /// Gets or sets the SDepartment list
        /// </summary>
        public virtual ICollection<Department> SDepartments { get; set; }

        #endregion
    }
}
