//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using HozestERP.Common.Utils;
using HozestERP.BusinessLogic.Infrastructure;
using HozestERP.BusinessLogic.CustomerManagement;

namespace HozestERP.BusinessLogic.ManageTableLog
{
    public partial class TableUpdateLog: BaseEntity
    {
        #region Primitive Properties
    
    	/// <summary>
        /// Gets or sets the LogID
        /// </summary>
        public int LogID { get; set; }
    
    	/// <summary>
        /// Gets or sets the RequestID
        /// </summary>
        public int RequestID { get; set; }
    
    	/// <summary>
        /// Gets or sets the FieldName
        /// </summary>
        public string FieldName { get; set; }
    
    	/// <summary>
        /// Gets or sets the OrginValue
        /// </summary>
        public string OrginValue { get; set; }
    
    	/// <summary>
        /// Gets or sets the NewValue
        /// </summary>
        public string NewValue { get; set; }
    
    	/// <summary>
        /// Gets or sets the OperatorID
        /// </summary>
        public int OperatorID { get; set; }

    	/// <summary>
        /// Gets or sets the UpdateTime
        /// </summary>
        public System.DateTime UpdateTime { get; set; }
    
    	/// <summary>
        /// Gets or sets the TableName
        /// </summary>
        public string TableName { get; set; }

        #endregion

        #region Custom Properties

        public CustomerInfo Operator
        {
            get
            {
                return IoC.Resolve<ICustomerInfoService>().GetCustomerInfoByID(this.OperatorID);
            }
        }


        public TableUpdatedLogFieldNameEnum FieldNameEnum
        {
            get
            {
                return (TableUpdatedLogFieldNameEnum)Enum.Parse(typeof(TableUpdatedLogFieldNameEnum)
                        , this.FieldName);
            }
        }

        #endregion
    }
}
