//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using HozestERP.BusinessLogic.Audit;
using HozestERP.BusinessLogic.CustomerManagement;
using HozestERP.BusinessLogic.Configuration.Settings;
using HozestERP.BusinessLogic.Media;
using HozestERP.BusinessLogic.Security;
using HozestERP.BusinessLogic.Enterprises;
using HozestERP.BusinessLogic.Codes;
using HozestERP.BusinessLogic.ModuleManagement;
using HozestERP.BusinessLogic.Notices;
using HozestERP.BusinessLogic.ManageProtal;
using HozestERP.BusinessLogic.ManageTableLog;
using HozestERP.BusinessLogic.ManageFile; 
using HozestERP.BusinessLogic.ManageFinance; 
using HozestERP.BusinessLogic.ManageProject; 
using HozestERP.BusinessLogic.ManageCustomerService; 
using HozestERP.BusinessLogic.ManageStock;
using HozestERP.BusinessLogic.ManageApplication;
using HozestERP.BusinessLogic.Customers;
using HozestERP.BusinessLogic.ManageBusiness;
using HozestERP.BusinessLogic.ManageInventory;
using HozestERP.BusinessLogic.ManageBulletin;
using HozestERP.BusinessLogic.ManageProductionOrder;

namespace HozestERP.BusinessLogic.Data
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class HozestERPObjectContext : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“HozestERPEntities”部分中的连接字符串初始化新 HozestERPEntities 对象。
        /// </summary>
        public HozestERPObjectContext() : base("name=HozestERPEntities", "HozestERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HozestERPEntities 对象。
        /// </summary>
        public HozestERPObjectContext(string connectionString) : base(connectionString, "HozestERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 HozestERPEntities 对象。
        /// </summary>
        public HozestERPObjectContext(EntityConnection connection) : base(connection, "HozestERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ACL> ACLs
        {
            get
            {
                if ((_ACLs == null))
                {
                    _ACLs = base.CreateObjectSet<ACL>("ACLs");
                }
                return _ACLs;
            }
        }
        private ObjectSet<ACL> _ACLs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ACLModule> ACLModules
        {
            get
            {
                if ((_ACLModules == null))
                {
                    _ACLModules = base.CreateObjectSet<ACLModule>("ACLModules");
                }
                return _ACLModules;
            }
        }
        private ObjectSet<ACLModule> _ACLModules;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ActivityLog> ActivityLogs
        {
            get
            {
                if ((_ActivityLogs == null))
                {
                    _ActivityLogs = base.CreateObjectSet<ActivityLog>("ActivityLogs");
                }
                return _ActivityLogs;
            }
        }
        private ObjectSet<ActivityLog> _ActivityLogs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ActivityLogType> ActivityLogTypes
        {
            get
            {
                if ((_ActivityLogTypes == null))
                {
                    _ActivityLogTypes = base.CreateObjectSet<ActivityLogType>("ActivityLogTypes");
                }
                return _ActivityLogTypes;
            }
        }
        private ObjectSet<ActivityLogType> _ActivityLogTypes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AreaCode> AreaCodes
        {
            get
            {
                if ((_AreaCodes == null))
                {
                    _AreaCodes = base.CreateObjectSet<AreaCode>("AreaCodes");
                }
                return _AreaCodes;
            }
        }
        private ObjectSet<AreaCode> _AreaCodes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BannedIpAddress> BannedIpAddresses
        {
            get
            {
                if ((_BannedIpAddresses == null))
                {
                    _BannedIpAddresses = base.CreateObjectSet<BannedIpAddress>("BannedIpAddresses");
                }
                return _BannedIpAddresses;
            }
        }
        private ObjectSet<BannedIpAddress> _BannedIpAddresses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BannedIpNetwork> BannedIpNetworks
        {
            get
            {
                if ((_BannedIpNetworks == null))
                {
                    _BannedIpNetworks = base.CreateObjectSet<BannedIpNetwork>("BannedIpNetworks");
                }
                return _BannedIpNetworks;
            }
        }
        private ObjectSet<BannedIpNetwork> _BannedIpNetworks;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CodeList> CodeLists
        {
            get
            {
                if ((_CodeLists == null))
                {
                    _CodeLists = base.CreateObjectSet<CodeList>("CodeLists");
                }
                return _CodeLists;
            }
        }
        private ObjectSet<CodeList> _CodeLists;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CodeType> CodeTypes
        {
            get
            {
                if ((_CodeTypes == null))
                {
                    _CodeTypes = base.CreateObjectSet<CodeType>("CodeTypes");
                }
                return _CodeTypes;
            }
        }
        private ObjectSet<CodeType> _CodeTypes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerAction> CustomerActions
        {
            get
            {
                if ((_CustomerActions == null))
                {
                    _CustomerActions = base.CreateObjectSet<CustomerAction>("CustomerActions");
                }
                return _CustomerActions;
            }
        }
        private ObjectSet<CustomerAction> _CustomerActions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerAttribute> CustomerAttributes
        {
            get
            {
                if ((_CustomerAttributes == null))
                {
                    _CustomerAttributes = base.CreateObjectSet<CustomerAttribute>("CustomerAttributes");
                }
                return _CustomerAttributes;
            }
        }
        private ObjectSet<CustomerAttribute> _CustomerAttributes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerRole> CustomerRoles
        {
            get
            {
                if ((_CustomerRoles == null))
                {
                    _CustomerRoles = base.CreateObjectSet<CustomerRole>("CustomerRoles");
                }
                return _CustomerRoles;
            }
        }
        private ObjectSet<CustomerRole> _CustomerRoles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerSession> CustomerSessions
        {
            get
            {
                if ((_CustomerSessions == null))
                {
                    _CustomerSessions = base.CreateObjectSet<CustomerSession>("CustomerSessions");
                }
                return _CustomerSessions;
            }
        }
        private ObjectSet<CustomerSession> _CustomerSessions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Enterprise> Enterprises
        {
            get
            {
                if ((_Enterprises == null))
                {
                    _Enterprises = base.CreateObjectSet<Enterprise>("Enterprises");
                }
                return _Enterprises;
            }
        }
        private ObjectSet<Enterprise> _Enterprises;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Log> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Log>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Log> _Logs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Picture> Pictures
        {
            get
            {
                if ((_Pictures == null))
                {
                    _Pictures = base.CreateObjectSet<Picture>("Pictures");
                }
                return _Pictures;
            }
        }
        private ObjectSet<Picture> _Pictures;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Portal> Portals
        {
            get
            {
                if ((_Portals == null))
                {
                    _Portals = base.CreateObjectSet<Portal>("Portals");
                }
                return _Portals;
            }
        }
        private ObjectSet<Portal> _Portals;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalColumn> PortalColumns
        {
            get
            {
                if ((_PortalColumns == null))
                {
                    _PortalColumns = base.CreateObjectSet<PortalColumn>("PortalColumns");
                }
                return _PortalColumns;
            }
        }
        private ObjectSet<PortalColumn> _PortalColumns;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PortalColumnNumber> PortalColumnNumbers
        {
            get
            {
                if ((_PortalColumnNumbers == null))
                {
                    _PortalColumnNumbers = base.CreateObjectSet<PortalColumnNumber>("PortalColumnNumbers");
                }
                return _PortalColumnNumbers;
            }
        }
        private ObjectSet<PortalColumnNumber> _PortalColumnNumbers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerInfo> CustomerInfoes
        {
            get
            {
                if ((_CustomerInfoes == null))
                {
                    _CustomerInfoes = base.CreateObjectSet<CustomerInfo>("CustomerInfoes");
                }
                return _CustomerInfoes;
            }
        }
        private ObjectSet<CustomerInfo> _CustomerInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UploadFile> UploadFiles
        {
            get
            {
                if ((_UploadFiles == null))
                {
                    _UploadFiles = base.CreateObjectSet<UploadFile>("UploadFiles");
                }
                return _UploadFiles;
            }
        }
        private ObjectSet<UploadFile> _UploadFiles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_AlertSettings> Sys_AlertSettings
        {
            get
            {
                if ((_Sys_AlertSettings == null))
                {
                    _Sys_AlertSettings = base.CreateObjectSet<Sys_AlertSettings>("Sys_AlertSettings");
                }
                return _Sys_AlertSettings;
            }
        }
        private ObjectSet<Sys_AlertSettings> _Sys_AlertSettings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_AlertTimeSet> Sys_AlertTimeSet
        {
            get
            {
                if ((_Sys_AlertTimeSet == null))
                {
                    _Sys_AlertTimeSet = base.CreateObjectSet<Sys_AlertTimeSet>("Sys_AlertTimeSet");
                }
                return _Sys_AlertTimeSet;
            }
        }
        private ObjectSet<Sys_AlertTimeSet> _Sys_AlertTimeSet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_StarSet> Sys_StarSet
        {
            get
            {
                if ((_Sys_StarSet == null))
                {
                    _Sys_StarSet = base.CreateObjectSet<Sys_StarSet>("Sys_StarSet");
                }
                return _Sys_StarSet;
            }
        }
        private ObjectSet<Sys_StarSet> _Sys_StarSet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_CustomerStar> Sys_CustomerStar
        {
            get
            {
                if ((_Sys_CustomerStar == null))
                {
                    _Sys_CustomerStar = base.CreateObjectSet<Sys_CustomerStar>("Sys_CustomerStar");
                }
                return _Sys_CustomerStar;
            }
        }
        private ObjectSet<Sys_CustomerStar> _Sys_CustomerStar;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TableUpdateLog> TableUpdateLogs
        {
            get
            {
                if ((_TableUpdateLogs == null))
                {
                    _TableUpdateLogs = base.CreateObjectSet<TableUpdateLog>("TableUpdateLogs");
                }
                return _TableUpdateLogs;
            }
        }
        private ObjectSet<TableUpdateLog> _TableUpdateLogs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Notice> Notices
        {
            get
            {
                if ((_Notices == null))
                {
                    _Notices = base.CreateObjectSet<Notice>("Notices");
                }
                return _Notices;
            }
        }
        private ObjectSet<Notice> _Notices;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMNickCustomerMapping> XMNickCustomerMappings
        {
            get
            {
                if ((_XMNickCustomerMappings == null))
                {
                    _XMNickCustomerMappings = base.CreateObjectSet<XMNickCustomerMapping>("XMNickCustomerMappings");
                }
                return _XMNickCustomerMappings;
            }
        }
        private ObjectSet<XMNickCustomerMapping> _XMNickCustomerMappings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AdvanceApplicationDetail> AdvanceApplicationDetails
        {
            get
            {
                if ((_AdvanceApplicationDetails == null))
                {
                    _AdvanceApplicationDetails = base.CreateObjectSet<AdvanceApplicationDetail>("AdvanceApplicationDetails");
                }
                return _AdvanceApplicationDetails;
            }
        }
        private ObjectSet<AdvanceApplicationDetail> _AdvanceApplicationDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<KFChatLog> KFChatLogs
        {
            get
            {
                if ((_KFChatLogs == null))
                {
                    _KFChatLogs = base.CreateObjectSet<KFChatLog>("KFChatLogs");
                }
                return _KFChatLogs;
            }
        }
        private ObjectSet<KFChatLog> _KFChatLogs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOrderInfoPlanRecord> XMOrderInfoPlanRecords
        {
            get
            {
                if ((_XMOrderInfoPlanRecords == null))
                {
                    _XMOrderInfoPlanRecords = base.CreateObjectSet<XMOrderInfoPlanRecord>("XMOrderInfoPlanRecords");
                }
                return _XMOrderInfoPlanRecords;
            }
        }
        private ObjectSet<XMOrderInfoPlanRecord> _XMOrderInfoPlanRecords;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AdvanceApplication> AdvanceApplications
        {
            get
            {
                if ((_AdvanceApplications == null))
                {
                    _AdvanceApplications = base.CreateObjectSet<AdvanceApplication>("AdvanceApplications");
                }
                return _AdvanceApplications;
            }
        }
        private ObjectSet<AdvanceApplication> _AdvanceApplications;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMScalpingApplication> XMScalpingApplications
        {
            get
            {
                if ((_XMScalpingApplications == null))
                {
                    _XMScalpingApplications = base.CreateObjectSet<XMScalpingApplication>("XMScalpingApplications");
                }
                return _XMScalpingApplications;
            }
        }
        private ObjectSet<XMScalpingApplication> _XMScalpingApplications;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMScalpingApplicationDetails> XMScalpingApplicationDetails
        {
            get
            {
                if ((_XMScalpingApplicationDetails == null))
                {
                    _XMScalpingApplicationDetails = base.CreateObjectSet<XMScalpingApplicationDetails>("XMScalpingApplicationDetails");
                }
                return _XMScalpingApplicationDetails;
            }
        }
        private ObjectSet<XMScalpingApplicationDetails> _XMScalpingApplicationDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOrderInfoOperatingRecord> XMOrderInfoOperatingRecords
        {
            get
            {
                if ((_XMOrderInfoOperatingRecords == null))
                {
                    _XMOrderInfoOperatingRecords = base.CreateObjectSet<XMOrderInfoOperatingRecord>("XMOrderInfoOperatingRecords");
                }
                return _XMOrderInfoOperatingRecords;
            }
        }
        private ObjectSet<XMOrderInfoOperatingRecord> _XMOrderInfoOperatingRecords;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCompanyCustom> XMCompanyCustoms
        {
            get
            {
                if ((_XMCompanyCustoms == null))
                {
                    _XMCompanyCustoms = base.CreateObjectSet<XMCompanyCustom>("XMCompanyCustoms");
                }
                return _XMCompanyCustoms;
            }
        }
        private ObjectSet<XMCompanyCustom> _XMCompanyCustoms;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMScalping> XMScalpings
        {
            get
            {
                if ((_XMScalpings == null))
                {
                    _XMScalpings = base.CreateObjectSet<XMScalping>("XMScalpings");
                }
                return _XMScalpings;
            }
        }
        private ObjectSet<XMScalping> _XMScalpings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPremiumsDetails> XMPremiumsDetails
        {
            get
            {
                if ((_XMPremiumsDetails == null))
                {
                    _XMPremiumsDetails = base.CreateObjectSet<XMPremiumsDetails>("XMPremiumsDetails");
                }
                return _XMPremiumsDetails;
            }
        }
        private ObjectSet<XMPremiumsDetails> _XMPremiumsDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCommunicationRecord> XMCommunicationRecords
        {
            get
            {
                if ((_XMCommunicationRecords == null))
                {
                    _XMCommunicationRecords = base.CreateObjectSet<XMCommunicationRecord>("XMCommunicationRecords");
                }
                return _XMCommunicationRecords;
            }
        }
        private ObjectSet<XMCommunicationRecord> _XMCommunicationRecords;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDeductionSetUp> XMDeductionSetUps
        {
            get
            {
                if ((_XMDeductionSetUps == null))
                {
                    _XMDeductionSetUps = base.CreateObjectSet<XMDeductionSetUp>("XMDeductionSetUps");
                }
                return _XMDeductionSetUps;
            }
        }
        private ObjectSet<XMDeductionSetUp> _XMDeductionSetUps;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCashBackApplication> XMCashBackApplications
        {
            get
            {
                if ((_XMCashBackApplications == null))
                {
                    _XMCashBackApplications = base.CreateObjectSet<XMCashBackApplication>("XMCashBackApplications");
                }
                return _XMCashBackApplications;
            }
        }
        private ObjectSet<XMCashBackApplication> _XMCashBackApplications;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCustomerServiceLevel> XMCustomerServiceLevels
        {
            get
            {
                if ((_XMCustomerServiceLevels == null))
                {
                    _XMCustomerServiceLevels = base.CreateObjectSet<XMCustomerServiceLevel>("XMCustomerServiceLevels");
                }
                return _XMCustomerServiceLevels;
            }
        }
        private ObjectSet<XMCustomerServiceLevel> _XMCustomerServiceLevels;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDSR> XMDSRs
        {
            get
            {
                if ((_XMDSRs == null))
                {
                    _XMDSRs = base.CreateObjectSet<XMDSR>("XMDSRs");
                }
                return _XMDSRs;
            }
        }
        private ObjectSet<XMDSR> _XMDSRs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMWangNo> XMWangNoes
        {
            get
            {
                if ((_XMWangNoes == null))
                {
                    _XMWangNoes = base.CreateObjectSet<XMWangNo>("XMWangNoes");
                }
                return _XMWangNoes;
            }
        }
        private ObjectSet<XMWangNo> _XMWangNoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCustomerWangNo> XMCustomerWangNoes
        {
            get
            {
                if ((_XMCustomerWangNoes == null))
                {
                    _XMCustomerWangNoes = base.CreateObjectSet<XMCustomerWangNo>("XMCustomerWangNoes");
                }
                return _XMCustomerWangNoes;
            }
        }
        private ObjectSet<XMCustomerWangNo> _XMCustomerWangNoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCustomerRank> XMCustomerRanks
        {
            get
            {
                if ((_XMCustomerRanks == null))
                {
                    _XMCustomerRanks = base.CreateObjectSet<XMCustomerRank>("XMCustomerRanks");
                }
                return _XMCustomerRanks;
            }
        }
        private ObjectSet<XMCustomerRank> _XMCustomerRanks;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOrderInfo> XMOrderInfoes
        {
            get
            {
                if ((_XMOrderInfoes == null))
                {
                    _XMOrderInfoes = base.CreateObjectSet<XMOrderInfo>("XMOrderInfoes");
                }
                return _XMOrderInfoes;
            }
        }
        private ObjectSet<XMOrderInfo> _XMOrderInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CWProject> CWProjects
        {
            get
            {
                if ((_CWProjects == null))
                {
                    _CWProjects = base.CreateObjectSet<CWProject>("CWProjects");
                }
                return _CWProjects;
            }
        }
        private ObjectSet<CWProject> _CWProjects;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProject> XMProjects
        {
            get
            {
                if ((_XMProjects == null))
                {
                    _XMProjects = base.CreateObjectSet<XMProject>("XMProjects");
                }
                return _XMProjects;
            }
        }
        private ObjectSet<XMProject> _XMProjects;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPost> XMPosts
        {
            get
            {
                if ((_XMPosts == null))
                {
                    _XMPosts = base.CreateObjectSet<XMPost>("XMPosts");
                }
                return _XMPosts;
            }
        }
        private ObjectSet<XMPost> _XMPosts;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Postshoplist> Postshoplists
        {
            get
            {
                if ((_Postshoplists == null))
                {
                    _Postshoplists = base.CreateObjectSet<Postshoplist>("Postshoplists");
                }
                return _Postshoplists;
            }
        }
        private ObjectSet<Postshoplist> _Postshoplists;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCombination> XMCombinations
        {
            get
            {
                if ((_XMCombinations == null))
                {
                    _XMCombinations = base.CreateObjectSet<XMCombination>("XMCombinations");
                }
                return _XMCombinations;
            }
        }
        private ObjectSet<XMCombination> _XMCombinations;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMCombinationDetails> XMCombinationDetails
        {
            get
            {
                if ((_XMCombinationDetails == null))
                {
                    _XMCombinationDetails = base.CreateObjectSet<XMCombinationDetails>("XMCombinationDetails");
                }
                return _XMCombinationDetails;
            }
        }
        private ObjectSet<XMCombinationDetails> _XMCombinationDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAfterSalesData> XMAfterSalesDatas
        {
            get
            {
                if ((_XMAfterSalesDatas == null))
                {
                    _XMAfterSalesDatas = base.CreateObjectSet<XMAfterSalesData>("XMAfterSalesDatas");
                }
                return _XMAfterSalesDatas;
            }
        }
        private ObjectSet<XMAfterSalesData> _XMAfterSalesDatas;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAdvertisingFee> XMAdvertisingFees
        {
            get
            {
                if ((_XMAdvertisingFees == null))
                {
                    _XMAdvertisingFees = base.CreateObjectSet<XMAdvertisingFee>("XMAdvertisingFees");
                }
                return _XMAdvertisingFees;
            }
        }
        private ObjectSet<XMAdvertisingFee> _XMAdvertisingFees;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMConsultationDetails> XMConsultationDetails
        {
            get
            {
                if ((_XMConsultationDetails == null))
                {
                    _XMConsultationDetails = base.CreateObjectSet<XMConsultationDetails>("XMConsultationDetails");
                }
                return _XMConsultationDetails;
            }
        }
        private ObjectSet<XMConsultationDetails> _XMConsultationDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProductCombination> XMProductCombinations
        {
            get
            {
                if ((_XMProductCombinations == null))
                {
                    _XMProductCombinations = base.CreateObjectSet<XMProductCombination>("XMProductCombinations");
                }
                return _XMProductCombinations;
            }
        }
        private ObjectSet<XMProductCombination> _XMProductCombinations;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMWarehouse> XMWarehouses
        {
            get
            {
                if ((_XMWarehouses == null))
                {
                    _XMWarehouses = base.CreateObjectSet<XMWarehouse>("XMWarehouses");
                }
                return _XMWarehouses;
            }
        }
        private ObjectSet<XMWarehouse> _XMWarehouses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMApplicationExchange> XMApplicationExchanges
        {
            get
            {
                if ((_XMApplicationExchanges == null))
                {
                    _XMApplicationExchanges = base.CreateObjectSet<XMApplicationExchange>("XMApplicationExchanges");
                }
                return _XMApplicationExchanges;
            }
        }
        private ObjectSet<XMApplicationExchange> _XMApplicationExchanges;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMGiftStorageRecord> XMGiftStorageRecords
        {
            get
            {
                if ((_XMGiftStorageRecords == null))
                {
                    _XMGiftStorageRecords = base.CreateObjectSet<XMGiftStorageRecord>("XMGiftStorageRecords");
                }
                return _XMGiftStorageRecords;
            }
        }
        private ObjectSet<XMGiftStorageRecord> _XMGiftStorageRecords;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimForm> XMClaimForms
        {
            get
            {
                if ((_XMClaimForms == null))
                {
                    _XMClaimForms = base.CreateObjectSet<XMClaimForm>("XMClaimForms");
                }
                return _XMClaimForms;
            }
        }
        private ObjectSet<XMClaimForm> _XMClaimForms;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimFormDetail> XMClaimFormDetails
        {
            get
            {
                if ((_XMClaimFormDetails == null))
                {
                    _XMClaimFormDetails = base.CreateObjectSet<XMClaimFormDetail>("XMClaimFormDetails");
                }
                return _XMClaimFormDetails;
            }
        }
        private ObjectSet<XMClaimFormDetail> _XMClaimFormDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMConsultation> XMConsultations
        {
            get
            {
                if ((_XMConsultations == null))
                {
                    _XMConsultations = base.CreateObjectSet<XMConsultation>("XMConsultations");
                }
                return _XMConsultations;
            }
        }
        private ObjectSet<XMConsultation> _XMConsultations;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMQuestionDetail> XMQuestionDetails
        {
            get
            {
                if ((_XMQuestionDetails == null))
                {
                    _XMQuestionDetails = base.CreateObjectSet<XMQuestionDetail>("XMQuestionDetails");
                }
                return _XMQuestionDetails;
            }
        }
        private ObjectSet<XMQuestionDetail> _XMQuestionDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMQuestion> XMQuestions
        {
            get
            {
                if ((_XMQuestions == null))
                {
                    _XMQuestions = base.CreateObjectSet<XMQuestion>("XMQuestions");
                }
                return _XMQuestions;
            }
        }
        private ObjectSet<XMQuestion> _XMQuestions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CustomerSalary> CustomerSalaries
        {
            get
            {
                if ((_CustomerSalaries == null))
                {
                    _CustomerSalaries = base.CreateObjectSet<CustomerSalary>("CustomerSalaries");
                }
                return _CustomerSalaries;
            }
        }
        private ObjectSet<CustomerSalary> _CustomerSalaries;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMBusinessData> XMBusinessDatas
        {
            get
            {
                if ((_XMBusinessDatas == null))
                {
                    _XMBusinessDatas = base.CreateObjectSet<XMBusinessData>("XMBusinessDatas");
                }
                return _XMBusinessDatas;
            }
        }
        private ObjectSet<XMBusinessData> _XMBusinessDatas;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMBusinessDataDetail> XMBusinessDataDetails
        {
            get
            {
                if ((_XMBusinessDataDetails == null))
                {
                    _XMBusinessDataDetails = base.CreateObjectSet<XMBusinessDataDetail>("XMBusinessDataDetails");
                }
                return _XMBusinessDataDetails;
            }
        }
        private ObjectSet<XMBusinessDataDetail> _XMBusinessDataDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMBusinessDataOther> XMBusinessDataOthers
        {
            get
            {
                if ((_XMBusinessDataOthers == null))
                {
                    _XMBusinessDataOthers = base.CreateObjectSet<XMBusinessDataOther>("XMBusinessDataOthers");
                }
                return _XMBusinessDataOthers;
            }
        }
        private ObjectSet<XMBusinessDataOther> _XMBusinessDataOthers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMNickMonthlyTarget> XMNickMonthlyTargets
        {
            get
            {
                if ((_XMNickMonthlyTargets == null))
                {
                    _XMNickMonthlyTargets = base.CreateObjectSet<XMNickMonthlyTarget>("XMNickMonthlyTargets");
                }
                return _XMNickMonthlyTargets;
            }
        }
        private ObjectSet<XMNickMonthlyTarget> _XMNickMonthlyTargets;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOtherMonthlyTarget> XMOtherMonthlyTargets
        {
            get
            {
                if ((_XMOtherMonthlyTargets == null))
                {
                    _XMOtherMonthlyTargets = base.CreateObjectSet<XMOtherMonthlyTarget>("XMOtherMonthlyTargets");
                }
                return _XMOtherMonthlyTargets;
            }
        }
        private ObjectSet<XMOtherMonthlyTarget> _XMOtherMonthlyTargets;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMNickAchieveValue> XMNickAchieveValue
        {
            get
            {
                if ((_XMNickAchieveValue == null))
                {
                    _XMNickAchieveValue = base.CreateObjectSet<XMNickAchieveValue>("XMNickAchieveValue");
                }
                return _XMNickAchieveValue;
            }
        }
        private ObjectSet<XMNickAchieveValue> _XMNickAchieveValue;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOrderInfoApp> XMOrderInfoApps
        {
            get
            {
                if ((_XMOrderInfoApps == null))
                {
                    _XMOrderInfoApps = base.CreateObjectSet<XMOrderInfoApp>("XMOrderInfoApps");
                }
                return _XMOrderInfoApps;
            }
        }
        private ObjectSet<XMOrderInfoApp> _XMOrderInfoApps;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMFinancialCapitalFlow> XMFinancialCapitalFlows
        {
            get
            {
                if ((_XMFinancialCapitalFlows == null))
                {
                    _XMFinancialCapitalFlows = base.CreateObjectSet<XMFinancialCapitalFlow>("XMFinancialCapitalFlows");
                }
                return _XMFinancialCapitalFlows;
            }
        }
        private ObjectSet<XMFinancialCapitalFlow> _XMFinancialCapitalFlows;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SocialSecurityFund> SocialSecurityFunds
        {
            get
            {
                if ((_SocialSecurityFunds == null))
                {
                    _SocialSecurityFunds = base.CreateObjectSet<SocialSecurityFund>("SocialSecurityFunds");
                }
                return _SocialSecurityFunds;
            }
        }
        private ObjectSet<SocialSecurityFund> _SocialSecurityFunds;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMFinancialField> XMFinancialFields
        {
            get
            {
                if ((_XMFinancialFields == null))
                {
                    _XMFinancialFields = base.CreateObjectSet<XMFinancialField>("XMFinancialFields");
                }
                return _XMFinancialFields;
            }
        }
        private ObjectSet<XMFinancialField> _XMFinancialFields;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOtherCostDetail> XMOtherCostDetails
        {
            get
            {
                if ((_XMOtherCostDetails == null))
                {
                    _XMOtherCostDetails = base.CreateObjectSet<XMOtherCostDetail>("XMOtherCostDetails");
                }
                return _XMOtherCostDetails;
            }
        }
        private ObjectSet<XMOtherCostDetail> _XMOtherCostDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAdvertingField> XMAdvertingFields
        {
            get
            {
                if ((_XMAdvertingFields == null))
                {
                    _XMAdvertingFields = base.CreateObjectSet<XMAdvertingField>("XMAdvertingFields");
                }
                return _XMAdvertingFields;
            }
        }
        private ObjectSet<XMAdvertingField> _XMAdvertingFields;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAdvertisingFeeDetail> XMAdvertisingFeeDetails
        {
            get
            {
                if ((_XMAdvertisingFeeDetails == null))
                {
                    _XMAdvertisingFeeDetails = base.CreateObjectSet<XMAdvertisingFeeDetail>("XMAdvertisingFeeDetails");
                }
                return _XMAdvertisingFeeDetails;
            }
        }
        private ObjectSet<XMAdvertisingFeeDetail> _XMAdvertisingFeeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMNickIncludeAdveringField> XMNickIncludeAdveringFields
        {
            get
            {
                if ((_XMNickIncludeAdveringFields == null))
                {
                    _XMNickIncludeAdveringFields = base.CreateObjectSet<XMNickIncludeAdveringField>("XMNickIncludeAdveringFields");
                }
                return _XMNickIncludeAdveringFields;
            }
        }
        private ObjectSet<XMNickIncludeAdveringField> _XMNickIncludeAdveringFields;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CWPlatformSpending> CWPlatformSpendings
        {
            get
            {
                if ((_CWPlatformSpendings == null))
                {
                    _CWPlatformSpendings = base.CreateObjectSet<CWPlatformSpending>("CWPlatformSpendings");
                }
                return _CWPlatformSpendings;
            }
        }
        private ObjectSet<CWPlatformSpending> _CWPlatformSpendings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMNick> XMNicks
        {
            get
            {
                if ((_XMNicks == null))
                {
                    _XMNicks = base.CreateObjectSet<XMNick>("XMNicks");
                }
                return _XMNicks;
            }
        }
        private ObjectSet<XMNick> _XMNicks;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMQuestionCategory> XMQuestionCategories
        {
            get
            {
                if ((_XMQuestionCategories == null))
                {
                    _XMQuestionCategories = base.CreateObjectSet<XMQuestionCategory>("XMQuestionCategories");
                }
                return _XMQuestionCategories;
            }
        }
        private ObjectSet<XMQuestionCategory> _XMQuestionCategories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CWProfit> CWProfits
        {
            get
            {
                if ((_CWProfits == null))
                {
                    _CWProfits = base.CreateObjectSet<CWProfit>("CWProfits");
                }
                return _CWProfits;
            }
        }
        private ObjectSet<CWProfit> _CWProfits;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CWStaffSpending> CWStaffSpendings
        {
            get
            {
                if ((_CWStaffSpendings == null))
                {
                    _CWStaffSpendings = base.CreateObjectSet<CWStaffSpending>("CWStaffSpendings");
                }
                return _CWStaffSpendings;
            }
        }
        private ObjectSet<CWStaffSpending> _CWStaffSpendings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSuppliers> XMSuppliers
        {
            get
            {
                if ((_XMSuppliers == null))
                {
                    _XMSuppliers = base.CreateObjectSet<XMSuppliers>("XMSuppliers");
                }
                return _XMSuppliers;
            }
        }
        private ObjectSet<XMSuppliers> _XMSuppliers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMLogisticsInfo> XMLogisticsInfoes
        {
            get
            {
                if ((_XMLogisticsInfoes == null))
                {
                    _XMLogisticsInfoes = base.CreateObjectSet<XMLogisticsInfo>("XMLogisticsInfoes");
                }
                return _XMLogisticsInfoes;
            }
        }
        private ObjectSet<XMLogisticsInfo> _XMLogisticsInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAdjustedInfo> XMAdjustedInfoes
        {
            get
            {
                if ((_XMAdjustedInfoes == null))
                {
                    _XMAdjustedInfoes = base.CreateObjectSet<XMAdjustedInfo>("XMAdjustedInfoes");
                }
                return _XMAdjustedInfoes;
            }
        }
        private ObjectSet<XMAdjustedInfo> _XMAdjustedInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAdjustedProductDetail> XMAdjustedProductDetails
        {
            get
            {
                if ((_XMAdjustedProductDetails == null))
                {
                    _XMAdjustedProductDetails = base.CreateObjectSet<XMAdjustedProductDetail>("XMAdjustedProductDetails");
                }
                return _XMAdjustedProductDetails;
            }
        }
        private ObjectSet<XMAdjustedProductDetail> _XMAdjustedProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInventoryInfo> XMInventoryInfoes
        {
            get
            {
                if ((_XMInventoryInfoes == null))
                {
                    _XMInventoryInfoes = base.CreateObjectSet<XMInventoryInfo>("XMInventoryInfoes");
                }
                return _XMInventoryInfoes;
            }
        }
        private ObjectSet<XMInventoryInfo> _XMInventoryInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPdInfo> XMPdInfoes
        {
            get
            {
                if ((_XMPdInfoes == null))
                {
                    _XMPdInfoes = base.CreateObjectSet<XMPdInfo>("XMPdInfoes");
                }
                return _XMPdInfoes;
            }
        }
        private ObjectSet<XMPdInfo> _XMPdInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPdInfoProductDetails> XMPdInfoProductDetails
        {
            get
            {
                if ((_XMPdInfoProductDetails == null))
                {
                    _XMPdInfoProductDetails = base.CreateObjectSet<XMPdInfoProductDetails>("XMPdInfoProductDetails");
                }
                return _XMPdInfoProductDetails;
            }
        }
        private ObjectSet<XMPdInfoProductDetails> _XMPdInfoProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleDelivery> XMSaleDeliveries
        {
            get
            {
                if ((_XMSaleDeliveries == null))
                {
                    _XMSaleDeliveries = base.CreateObjectSet<XMSaleDelivery>("XMSaleDeliveries");
                }
                return _XMSaleDeliveries;
            }
        }
        private ObjectSet<XMSaleDelivery> _XMSaleDeliveries;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleDeliveryProductDetails> XMSaleDeliveryProductDetails
        {
            get
            {
                if ((_XMSaleDeliveryProductDetails == null))
                {
                    _XMSaleDeliveryProductDetails = base.CreateObjectSet<XMSaleDeliveryProductDetails>("XMSaleDeliveryProductDetails");
                }
                return _XMSaleDeliveryProductDetails;
            }
        }
        private ObjectSet<XMSaleDeliveryProductDetails> _XMSaleDeliveryProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleInfoProductDetails> XMSaleInfoProductDetails
        {
            get
            {
                if ((_XMSaleInfoProductDetails == null))
                {
                    _XMSaleInfoProductDetails = base.CreateObjectSet<XMSaleInfoProductDetails>("XMSaleInfoProductDetails");
                }
                return _XMSaleInfoProductDetails;
            }
        }
        private ObjectSet<XMSaleInfoProductDetails> _XMSaleInfoProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleReturnProductDetails> XMSaleReturnProductDetails
        {
            get
            {
                if ((_XMSaleReturnProductDetails == null))
                {
                    _XMSaleReturnProductDetails = base.CreateObjectSet<XMSaleReturnProductDetails>("XMSaleReturnProductDetails");
                }
                return _XMSaleReturnProductDetails;
            }
        }
        private ObjectSet<XMSaleReturnProductDetails> _XMSaleReturnProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMStorage> XMStorages
        {
            get
            {
                if ((_XMStorages == null))
                {
                    _XMStorages = base.CreateObjectSet<XMStorage>("XMStorages");
                }
                return _XMStorages;
            }
        }
        private ObjectSet<XMStorage> _XMStorages;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPurchaseProductDetails> XMPurchaseProductDetails
        {
            get
            {
                if ((_XMPurchaseProductDetails == null))
                {
                    _XMPurchaseProductDetails = base.CreateObjectSet<XMPurchaseProductDetails>("XMPurchaseProductDetails");
                }
                return _XMPurchaseProductDetails;
            }
        }
        private ObjectSet<XMPurchaseProductDetails> _XMPurchaseProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMStorageProductDetails> XMStorageProductDetails
        {
            get
            {
                if ((_XMStorageProductDetails == null))
                {
                    _XMStorageProductDetails = base.CreateObjectSet<XMStorageProductDetails>("XMStorageProductDetails");
                }
                return _XMStorageProductDetails;
            }
        }
        private ObjectSet<XMStorageProductDetails> _XMStorageProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleReturn> XMSaleReturns
        {
            get
            {
                if ((_XMSaleReturns == null))
                {
                    _XMSaleReturns = base.CreateObjectSet<XMSaleReturn>("XMSaleReturns");
                }
                return _XMSaleReturns;
            }
        }
        private ObjectSet<XMSaleReturn> _XMSaleReturns;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<LogisticsAging> LogisticsAgings
        {
            get
            {
                if ((_LogisticsAgings == null))
                {
                    _LogisticsAgings = base.CreateObjectSet<LogisticsAging>("LogisticsAgings");
                }
                return _LogisticsAgings;
            }
        }
        private ObjectSet<LogisticsAging> _LogisticsAgings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInventoryLedger> XMInventoryLedgers
        {
            get
            {
                if ((_XMInventoryLedgers == null))
                {
                    _XMInventoryLedgers = base.CreateObjectSet<XMInventoryLedger>("XMInventoryLedgers");
                }
                return _XMInventoryLedgers;
            }
        }
        private ObjectSet<XMInventoryLedger> _XMInventoryLedgers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInventoryLedgerDetail> XMInventoryLedgerDetails
        {
            get
            {
                if ((_XMInventoryLedgerDetails == null))
                {
                    _XMInventoryLedgerDetails = base.CreateObjectSet<XMInventoryLedgerDetail>("XMInventoryLedgerDetails");
                }
                return _XMInventoryLedgerDetails;
            }
        }
        private ObjectSet<XMInventoryLedgerDetail> _XMInventoryLedgerDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMWareHouses> XMWareHouses
        {
            get
            {
                if ((_XMWareHouses == null))
                {
                    _XMWareHouses = base.CreateObjectSet<XMWareHouses>("XMWareHouses");
                }
                return _XMWareHouses;
            }
        }
        private ObjectSet<XMWareHouses> _XMWareHouses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ProvinceWarehouse> ProvinceWarehouses
        {
            get
            {
                if ((_ProvinceWarehouses == null))
                {
                    _ProvinceWarehouses = base.CreateObjectSet<ProvinceWarehouse>("ProvinceWarehouses");
                }
                return _ProvinceWarehouses;
            }
        }
        private ObjectSet<ProvinceWarehouse> _ProvinceWarehouses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAllocateInfo> XMAllocateInfoes
        {
            get
            {
                if ((_XMAllocateInfoes == null))
                {
                    _XMAllocateInfoes = base.CreateObjectSet<XMAllocateInfo>("XMAllocateInfoes");
                }
                return _XMAllocateInfoes;
            }
        }
        private ObjectSet<XMAllocateInfo> _XMAllocateInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAllocateProductDetails> XMAllocateProductDetails
        {
            get
            {
                if ((_XMAllocateProductDetails == null))
                {
                    _XMAllocateProductDetails = base.CreateObjectSet<XMAllocateProductDetails>("XMAllocateProductDetails");
                }
                return _XMAllocateProductDetails;
            }
        }
        private ObjectSet<XMAllocateProductDetails> _XMAllocateProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMOrderInfoProductDetails> XMOrderInfoProductDetails
        {
            get
            {
                if ((_XMOrderInfoProductDetails == null))
                {
                    _XMOrderInfoProductDetails = base.CreateObjectSet<XMOrderInfoProductDetails>("XMOrderInfoProductDetails");
                }
                return _XMOrderInfoProductDetails;
            }
        }
        private ObjectSet<XMOrderInfoProductDetails> _XMOrderInfoProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMStorageProductBarCodeDetail> XMStorageProductBarCodeDetails
        {
            get
            {
                if ((_XMStorageProductBarCodeDetails == null))
                {
                    _XMStorageProductBarCodeDetails = base.CreateObjectSet<XMStorageProductBarCodeDetail>("XMStorageProductBarCodeDetails");
                }
                return _XMStorageProductBarCodeDetails;
            }
        }
        private ObjectSet<XMStorageProductBarCodeDetail> _XMStorageProductBarCodeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMXLMInventory> XMXLMInventories
        {
            get
            {
                if ((_XMXLMInventories == null))
                {
                    _XMXLMInventories = base.CreateObjectSet<XMXLMInventory>("XMXLMInventories");
                }
                return _XMXLMInventories;
            }
        }
        private ObjectSet<XMXLMInventory> _XMXLMInventories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMAllocateProductBarCodeDetail> XMAllocateProductBarCodeDetails
        {
            get
            {
                if ((_XMAllocateProductBarCodeDetails == null))
                {
                    _XMAllocateProductBarCodeDetails = base.CreateObjectSet<XMAllocateProductBarCodeDetail>("XMAllocateProductBarCodeDetails");
                }
                return _XMAllocateProductBarCodeDetails;
            }
        }
        private ObjectSet<XMAllocateProductBarCodeDetail> _XMAllocateProductBarCodeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleDeliveryBarCodeDetail> XMSaleDeliveryBarCodeDetails
        {
            get
            {
                if ((_XMSaleDeliveryBarCodeDetails == null))
                {
                    _XMSaleDeliveryBarCodeDetails = base.CreateObjectSet<XMSaleDeliveryBarCodeDetail>("XMSaleDeliveryBarCodeDetails");
                }
                return _XMSaleDeliveryBarCodeDetails;
            }
        }
        private ObjectSet<XMSaleDeliveryBarCodeDetail> _XMSaleDeliveryBarCodeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleReturnBarCodeDetail> XMSaleReturnBarCodeDetails
        {
            get
            {
                if ((_XMSaleReturnBarCodeDetails == null))
                {
                    _XMSaleReturnBarCodeDetails = base.CreateObjectSet<XMSaleReturnBarCodeDetail>("XMSaleReturnBarCodeDetails");
                }
                return _XMSaleReturnBarCodeDetails;
            }
        }
        private ObjectSet<XMSaleReturnBarCodeDetail> _XMSaleReturnBarCodeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInventoryBarcodeDetail> XMInventoryBarcodeDetails
        {
            get
            {
                if ((_XMInventoryBarcodeDetails == null))
                {
                    _XMInventoryBarcodeDetails = base.CreateObjectSet<XMInventoryBarcodeDetail>("XMInventoryBarcodeDetails");
                }
                return _XMInventoryBarcodeDetails;
            }
        }
        private ObjectSet<XMInventoryBarcodeDetail> _XMInventoryBarcodeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPaymentApply> XMPaymentApplies
        {
            get
            {
                if ((_XMPaymentApplies == null))
                {
                    _XMPaymentApplies = base.CreateObjectSet<XMPaymentApply>("XMPaymentApplies");
                }
                return _XMPaymentApplies;
            }
        }
        private ObjectSet<XMPaymentApply> _XMPaymentApplies;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSaleInfo> XMSaleInfoes
        {
            get
            {
                if ((_XMSaleInfoes == null))
                {
                    _XMSaleInfoes = base.CreateObjectSet<XMSaleInfo>("XMSaleInfoes");
                }
                return _XMSaleInfoes;
            }
        }
        private ObjectSet<XMSaleInfo> _XMSaleInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMActivityType> XMActivityTypes
        {
            get
            {
                if ((_XMActivityTypes == null))
                {
                    _XMActivityTypes = base.CreateObjectSet<XMActivityType>("XMActivityTypes");
                }
                return _XMActivityTypes;
            }
        }
        private ObjectSet<XMActivityType> _XMActivityTypes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMActivity> XMActivities
        {
            get
            {
                if ((_XMActivities == null))
                {
                    _XMActivities = base.CreateObjectSet<XMActivity>("XMActivities");
                }
                return _XMActivities;
            }
        }
        private ObjectSet<XMActivity> _XMActivities;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDailySaleInfo> XMDailySaleInfoes
        {
            get
            {
                if ((_XMDailySaleInfoes == null))
                {
                    _XMDailySaleInfoes = base.CreateObjectSet<XMDailySaleInfo>("XMDailySaleInfoes");
                }
                return _XMDailySaleInfoes;
            }
        }
        private ObjectSet<XMDailySaleInfo> _XMDailySaleInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ProvinceWarehouseSpare> ProvinceWarehouseSpares
        {
            get
            {
                if ((_ProvinceWarehouseSpares == null))
                {
                    _ProvinceWarehouseSpares = base.CreateObjectSet<ProvinceWarehouseSpare>("ProvinceWarehouseSpares");
                }
                return _ProvinceWarehouseSpares;
            }
        }
        private ObjectSet<ProvinceWarehouseSpare> _ProvinceWarehouseSpares;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMSpareAddress> XMSpareAddresses
        {
            get
            {
                if ((_XMSpareAddresses == null))
                {
                    _XMSpareAddresses = base.CreateObjectSet<XMSpareAddress>("XMSpareAddresses");
                }
                return _XMSpareAddresses;
            }
        }
        private ObjectSet<XMSpareAddress> _XMSpareAddresses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimInfoDetail> XMClaimInfoDetails
        {
            get
            {
                if ((_XMClaimInfoDetails == null))
                {
                    _XMClaimInfoDetails = base.CreateObjectSet<XMClaimInfoDetail>("XMClaimInfoDetails");
                }
                return _XMClaimInfoDetails;
            }
        }
        private ObjectSet<XMClaimInfoDetail> _XMClaimInfoDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInvoiceInfoDetail> XMInvoiceInfoDetails
        {
            get
            {
                if ((_XMInvoiceInfoDetails == null))
                {
                    _XMInvoiceInfoDetails = base.CreateObjectSet<XMInvoiceInfoDetail>("XMInvoiceInfoDetails");
                }
                return _XMInvoiceInfoDetails;
            }
        }
        private ObjectSet<XMInvoiceInfoDetail> _XMInvoiceInfoDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInvoiceInfo> XMInvoiceInfoes
        {
            get
            {
                if ((_XMInvoiceInfoes == null))
                {
                    _XMInvoiceInfoes = base.CreateObjectSet<XMInvoiceInfo>("XMInvoiceInfoes");
                }
                return _XMInvoiceInfoes;
            }
        }
        private ObjectSet<XMInvoiceInfo> _XMInvoiceInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimInfo> XMClaimInfoes
        {
            get
            {
                if ((_XMClaimInfoes == null))
                {
                    _XMClaimInfoes = base.CreateObjectSet<XMClaimInfo>("XMClaimInfoes");
                }
                return _XMClaimInfoes;
            }
        }
        private ObjectSet<XMClaimInfo> _XMClaimInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInventoryInfoStatistics> XMInventoryInfoStatistics
        {
            get
            {
                if ((_XMInventoryInfoStatistics == null))
                {
                    _XMInventoryInfoStatistics = base.CreateObjectSet<XMInventoryInfoStatistics>("XMInventoryInfoStatistics");
                }
                return _XMInventoryInfoStatistics;
            }
        }
        private ObjectSet<XMInventoryInfoStatistics> _XMInventoryInfoStatistics;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMExpressManagement> XMExpressManagements
        {
            get
            {
                if ((_XMExpressManagements == null))
                {
                    _XMExpressManagements = base.CreateObjectSet<XMExpressManagement>("XMExpressManagements");
                }
                return _XMExpressManagements;
            }
        }
        private ObjectSet<XMExpressManagement> _XMExpressManagements;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMExpressListManagement> XMExpressListManagements
        {
            get
            {
                if ((_XMExpressListManagements == null))
                {
                    _XMExpressListManagements = base.CreateObjectSet<XMExpressListManagement>("XMExpressListManagements");
                }
                return _XMExpressListManagements;
            }
        }
        private ObjectSet<XMExpressListManagement> _XMExpressListManagements;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Bulletin> Bulletins
        {
            get
            {
                if ((_Bulletins == null))
                {
                    _Bulletins = base.CreateObjectSet<Bulletin>("Bulletins");
                }
                return _Bulletins;
            }
        }
        private ObjectSet<Bulletin> _Bulletins;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPurchaseRejected> XMPurchaseRejecteds
        {
            get
            {
                if ((_XMPurchaseRejecteds == null))
                {
                    _XMPurchaseRejecteds = base.CreateObjectSet<XMPurchaseRejected>("XMPurchaseRejecteds");
                }
                return _XMPurchaseRejecteds;
            }
        }
        private ObjectSet<XMPurchaseRejected> _XMPurchaseRejecteds;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimInfoProductDetails> XMClaimInfoProductDetails
        {
            get
            {
                if ((_XMClaimInfoProductDetails == null))
                {
                    _XMClaimInfoProductDetails = base.CreateObjectSet<XMClaimInfoProductDetails>("XMClaimInfoProductDetails");
                }
                return _XMClaimInfoProductDetails;
            }
        }
        private ObjectSet<XMClaimInfoProductDetails> _XMClaimInfoProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimInfoPicture> XMClaimInfoPictures
        {
            get
            {
                if ((_XMClaimInfoPictures == null))
                {
                    _XMClaimInfoPictures = base.CreateObjectSet<XMClaimInfoPicture>("XMClaimInfoPictures");
                }
                return _XMClaimInfoPictures;
            }
        }
        private ObjectSet<XMClaimInfoPicture> _XMClaimInfoPictures;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPremiums> XMPremiums
        {
            get
            {
                if ((_XMPremiums == null))
                {
                    _XMPremiums = base.CreateObjectSet<XMPremiums>("XMPremiums");
                }
                return _XMPremiums;
            }
        }
        private ObjectSet<XMPremiums> _XMPremiums;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMJDZYSaleCoefficients> XMJDZYSaleCoefficients
        {
            get
            {
                if ((_XMJDZYSaleCoefficients == null))
                {
                    _XMJDZYSaleCoefficients = base.CreateObjectSet<XMJDZYSaleCoefficients>("XMJDZYSaleCoefficients");
                }
                return _XMJDZYSaleCoefficients;
            }
        }
        private ObjectSet<XMJDZYSaleCoefficients> _XMJDZYSaleCoefficients;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDeliveryProductInventory> XMDeliveryProductInventories
        {
            get
            {
                if ((_XMDeliveryProductInventories == null))
                {
                    _XMDeliveryProductInventories = base.CreateObjectSet<XMDeliveryProductInventory>("XMDeliveryProductInventories");
                }
                return _XMDeliveryProductInventories;
            }
        }
        private ObjectSet<XMDeliveryProductInventory> _XMDeliveryProductInventories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMJDRealTimeInventory> XMJDRealTimeInventories
        {
            get
            {
                if ((_XMJDRealTimeInventories == null))
                {
                    _XMJDRealTimeInventories = base.CreateObjectSet<XMJDRealTimeInventory>("XMJDRealTimeInventories");
                }
                return _XMJDRealTimeInventories;
            }
        }
        private ObjectSet<XMJDRealTimeInventory> _XMJDRealTimeInventories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProductionOrder> XMProductionOrders
        {
            get
            {
                if ((_XMProductionOrders == null))
                {
                    _XMProductionOrders = base.CreateObjectSet<XMProductionOrder>("XMProductionOrders");
                }
                return _XMProductionOrders;
            }
        }
        private ObjectSet<XMProductionOrder> _XMProductionOrders;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProductionOrderDetails> XMProductionOrderDetails
        {
            get
            {
                if ((_XMProductionOrderDetails == null))
                {
                    _XMProductionOrderDetails = base.CreateObjectSet<XMProductionOrderDetails>("XMProductionOrderDetails");
                }
                return _XMProductionOrderDetails;
            }
        }
        private ObjectSet<XMProductionOrderDetails> _XMProductionOrderDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMJDSaleRejectedProductDetail> XMJDSaleRejectedProductDetails
        {
            get
            {
                if ((_XMJDSaleRejectedProductDetails == null))
                {
                    _XMJDSaleRejectedProductDetails = base.CreateObjectSet<XMJDSaleRejectedProductDetail>("XMJDSaleRejectedProductDetails");
                }
                return _XMJDSaleRejectedProductDetails;
            }
        }
        private ObjectSet<XMJDSaleRejectedProductDetail> _XMJDSaleRejectedProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPurchaseRejectedProductDetails> XMPurchaseRejectedProductDetails
        {
            get
            {
                if ((_XMPurchaseRejectedProductDetails == null))
                {
                    _XMPurchaseRejectedProductDetails = base.CreateObjectSet<XMPurchaseRejectedProductDetails>("XMPurchaseRejectedProductDetails");
                }
                return _XMPurchaseRejectedProductDetails;
            }
        }
        private ObjectSet<XMPurchaseRejectedProductDetails> _XMPurchaseRejectedProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMTypeTest> XMTypeTests
        {
            get
            {
                if ((_XMTypeTests == null))
                {
                    _XMTypeTests = base.CreateObjectSet<XMTypeTest>("XMTypeTests");
                }
                return _XMTypeTests;
            }
        }
        private ObjectSet<XMTypeTest> _XMTypeTests;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMZMDemand> XMZMDemands
        {
            get
            {
                if ((_XMZMDemands == null))
                {
                    _XMZMDemands = base.CreateObjectSet<XMZMDemand>("XMZMDemands");
                }
                return _XMZMDemands;
            }
        }
        private ObjectSet<XMZMDemand> _XMZMDemands;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMLogisticsFeeBranch> XMLogisticsFeeBranches
        {
            get
            {
                if ((_XMLogisticsFeeBranches == null))
                {
                    _XMLogisticsFeeBranches = base.CreateObjectSet<XMLogisticsFeeBranch>("XMLogisticsFeeBranches");
                }
                return _XMLogisticsFeeBranches;
            }
        }
        private ObjectSet<XMLogisticsFeeBranch> _XMLogisticsFeeBranches;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMLogisticsFeeDetail> XMLogisticsFeeDetails
        {
            get
            {
                if ((_XMLogisticsFeeDetails == null))
                {
                    _XMLogisticsFeeDetails = base.CreateObjectSet<XMLogisticsFeeDetail>("XMLogisticsFeeDetails");
                }
                return _XMLogisticsFeeDetails;
            }
        }
        private ObjectSet<XMLogisticsFeeDetail> _XMLogisticsFeeDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMLogisticsFeeMain> XMLogisticsFeeMains
        {
            get
            {
                if ((_XMLogisticsFeeMains == null))
                {
                    _XMLogisticsFeeMains = base.CreateObjectSet<XMLogisticsFeeMain>("XMLogisticsFeeMains");
                }
                return _XMLogisticsFeeMains;
            }
        }
        private ObjectSet<XMLogisticsFeeMain> _XMLogisticsFeeMains;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMInstallationList> XMInstallationLists
        {
            get
            {
                if ((_XMInstallationLists == null))
                {
                    _XMInstallationLists = base.CreateObjectSet<XMInstallationList>("XMInstallationLists");
                }
                return _XMInstallationLists;
            }
        }
        private ObjectSet<XMInstallationList> _XMInstallationLists;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMZMReservation> XMZMReservations
        {
            get
            {
                if ((_XMZMReservations == null))
                {
                    _XMZMReservations = base.CreateObjectSet<XMZMReservation>("XMZMReservations");
                }
                return _XMZMReservations;
            }
        }
        private ObjectSet<XMZMReservation> _XMZMReservations;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMClaimReason> XMClaimReasons
        {
            get
            {
                if ((_XMClaimReasons == null))
                {
                    _XMClaimReasons = base.CreateObjectSet<XMClaimReason>("XMClaimReasons");
                }
                return _XMClaimReasons;
            }
        }
        private ObjectSet<XMClaimReason> _XMClaimReasons;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMWorkerInfo> XMWorkerInfoes
        {
            get
            {
                if ((_XMWorkerInfoes == null))
                {
                    _XMWorkerInfoes = base.CreateObjectSet<XMWorkerInfo>("XMWorkerInfoes");
                }
                return _XMWorkerInfoes;
            }
        }
        private ObjectSet<XMWorkerInfo> _XMWorkerInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMLogisticsCost> XMLogisticsCosts
        {
            get
            {
                if ((_XMLogisticsCosts == null))
                {
                    _XMLogisticsCosts = base.CreateObjectSet<XMLogisticsCost>("XMLogisticsCosts");
                }
                return _XMLogisticsCosts;
            }
        }
        private ObjectSet<XMLogisticsCost> _XMLogisticsCosts;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMJDSaleRejected> XMJDSaleRejecteds
        {
            get
            {
                if ((_XMJDSaleRejecteds == null))
                {
                    _XMJDSaleRejecteds = base.CreateObjectSet<XMJDSaleRejected>("XMJDSaleRejecteds");
                }
                return _XMJDSaleRejecteds;
            }
        }
        private ObjectSet<XMJDSaleRejected> _XMJDSaleRejecteds;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProductDetails> XMProductDetails
        {
            get
            {
                if ((_XMProductDetails == null))
                {
                    _XMProductDetails = base.CreateObjectSet<XMProductDetails>("XMProductDetails");
                }
                return _XMProductDetails;
            }
        }
        private ObjectSet<XMProductDetails> _XMProductDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMPurchase> XMPurchases
        {
            get
            {
                if ((_XMPurchases == null))
                {
                    _XMPurchases = base.CreateObjectSet<XMPurchase>("XMPurchases");
                }
                return _XMPurchases;
            }
        }
        private ObjectSet<XMPurchase> _XMPurchases;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMIncludeFields> XMIncludeFields
        {
            get
            {
                if ((_XMIncludeFields == null))
                {
                    _XMIncludeFields = base.CreateObjectSet<XMIncludeFields>("XMIncludeFields");
                }
                return _XMIncludeFields;
            }
        }
        private ObjectSet<XMIncludeFields> _XMIncludeFields;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProjectCostDetail> XMProjectCostDetails
        {
            get
            {
                if ((_XMProjectCostDetails == null))
                {
                    _XMProjectCostDetails = base.CreateObjectSet<XMProjectCostDetail>("XMProjectCostDetails");
                }
                return _XMProjectCostDetails;
            }
        }
        private ObjectSet<XMProjectCostDetail> _XMProjectCostDetails;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMApplication> XMApplications
        {
            get
            {
                if ((_XMApplications == null))
                {
                    _XMApplications = base.CreateObjectSet<XMApplication>("XMApplications");
                }
                return _XMApplications;
            }
        }
        private ObjectSet<XMApplication> _XMApplications;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMProduct> XMProducts
        {
            get
            {
                if ((_XMProducts == null))
                {
                    _XMProducts = base.CreateObjectSet<XMProduct>("XMProducts");
                }
                return _XMProducts;
            }
        }
        private ObjectSet<XMProduct> _XMProducts;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMBills> XMBills
        {
            get
            {
                if ((_XMBills == null))
                {
                    _XMBills = base.CreateObjectSet<XMBills>("XMBills");
                }
                return _XMBills;
            }
        }
        private ObjectSet<XMBills> _XMBills;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDelivery> XMDeliveries
        {
            get
            {
                if ((_XMDeliveries == null))
                {
                    _XMDeliveries = base.CreateObjectSet<XMDelivery>("XMDeliveries");
                }
                return _XMDeliveries;
            }
        }
        private ObjectSet<XMDelivery> _XMDeliveries;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XMDeliveryDetails> XMDeliveryDetails
        {
            get
            {
                if ((_XMDeliveryDetails == null))
                {
                    _XMDeliveryDetails = base.CreateObjectSet<XMDeliveryDetails>("XMDeliveryDetails");
                }
                return _XMDeliveryDetails;
            }
        }
        private ObjectSet<XMDeliveryDetails> _XMDeliveryDetails;

        #endregion
    }
    

    #endregion
    
    
}
